;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		LaTeX-insert-left-brace
		TeX-insert-backslash
		c-electric-brace
		c-electric-colon
		c-electric-delete-forward
		c-electric-lt-gt
		org-beginning-of-line
		org-cycle
		org-delete-char
		org-end-of-line
		org-return
		org-self-insert-command
		org-yank
		rjsx-delete-creates-full-tag
		))

(setq mc/cmds-to-run-once
      '(
		))
