;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		org-delete-char
		org-self-insert-command
		rjsx-delete-creates-full-tag
		))

(setq mc/cmds-to-run-once
      '(
		))
